// pdf-lib/html2canvas/jspdf импортируются динамически внутри функций ниже —
// это самые тяжёлые зависимости в бандле (~1.7 МБ несжатого JS суммарно),
// нужны только когда пользователь реально жмёт экспорт/печать, не при каждом
// открытии страницы.
import { DocumentData } from '../types';

const oklchCache = new Map<string, string>();

/**
 * Converts OKLCH color strings (generated by Tailwind CSS v4) to standard rgb(...) format
 * using browser's native computed style engine.
 */
function convertOklchToRgb(oklchStr: string): string {
  if (!oklchStr || !oklchStr.includes('oklch')) return oklchStr;
  if (oklchCache.has(oklchStr)) return oklchCache.get(oklchStr)!;

  try {
    const tempDiv = document.createElement('div');
    tempDiv.style.color = oklchStr;
    document.body.appendChild(tempDiv);
    const computed = window.getComputedStyle(tempDiv).color;
    document.body.removeChild(tempDiv);

    if (computed && !computed.includes('oklch') && computed !== '') {
      oklchCache.set(oklchStr, computed);
      return computed;
    }
  } catch (e) {
    // fallback
  }

  const fallback = 'rgb(30, 41, 59)';
  oklchCache.set(oklchStr, fallback);
  return fallback;
}

/**
 * Generates ArrayBuffer for the main A4 document preview sheet
 */
export async function generateMainDocumentPdfArrayBuffer(
  docData: DocumentData
): Promise<{ buffer: ArrayBuffer; filename: string } | null> {
  const el = document.getElementById('document-a4-sheet');
  if (!el) {
    console.error('Element #document-a4-sheet not found in DOM');
    return null;
  }

  const html2canvas = (await import('html2canvas')).default;
  const { default: jsPDF } = await import('jspdf');

  const canvas = await html2canvas(el, {
    scale: 2,
    useCORS: true,
    allowTaint: false,
    backgroundColor: '#ffffff',
    logging: false,
    onclone: (clonedDoc, clonedEl) => {
      // Reset transform so it captures at exact 1:1 scale
      if (clonedEl) {
        clonedEl.style.transform = 'none';
      }

      // 1. Sanitize all <style> elements in cloned document
      const styleElements = clonedDoc.querySelectorAll('style');
      styleElements.forEach((styleEl) => {
        if (styleEl.textContent && styleEl.textContent.includes('oklch')) {
          styleEl.textContent = styleEl.textContent.replace(/oklch\([^)]+\)/gi, (m) => convertOklchToRgb(m));
        }
      });

      // 2. Sanitize inline styles & computed styles for target element and children
      const allElements = clonedEl
        ? [clonedEl, ...Array.from(clonedEl.querySelectorAll('*'))]
        : Array.from(clonedDoc.querySelectorAll('*'));

      allElements.forEach((node) => {
        const nodeEl = node as HTMLElement;
        if (!nodeEl || !nodeEl.style) return;

        const styleAttr = nodeEl.getAttribute('style');
        if (styleAttr && styleAttr.includes('oklch')) {
          nodeEl.setAttribute('style', styleAttr.replace(/oklch\([^)]+\)/gi, (m) => convertOklchToRgb(m)));
        }

        try {
          const computed = window.getComputedStyle(nodeEl);
          ['color', 'backgroundColor', 'borderColor', 'outlineColor', 'fill', 'stroke'].forEach((prop) => {
            const val = computed.getPropertyValue(prop);
            if (val && val.includes('oklch')) {
              nodeEl.style.setProperty(prop, convertOklchToRgb(val), 'important');
            }
          });
        } catch (e) {
          // ignore computed style errors
        }
      });
    },
  });

  let imgData = '';
  try {
    imgData = canvas.toDataURL('image/jpeg', 0.95);
  } catch (e) {
    console.warn('JPEG canvas capture failed, using PNG fallback:', e);
    imgData = canvas.toDataURL('image/png');
  }

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
    compress: true,
  });

  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();

  pdf.addImage(imgData, 'JPEG', 0, 0, pdfWidth, pdfHeight);

  const cleanDocType = (docData.docType || 'Документ').trim().replace(/[\\/:*?"<>|]/g, '_');
  const cleanSubject = (docData.docSubject || '').trim().slice(0, 30).replace(/[\\/:*?"<>|]/g, '_');
  const dateStr = (docData.date || new Date().toLocaleDateString('ru-RU')).replace(/\./g, '_');

  const filename = cleanSubject
    ? `${cleanDocType}_${cleanSubject}_${dateStr}.pdf`
    : `${cleanDocType}_${dateStr}.pdf`;

  return {
    buffer: pdf.output('arraybuffer'),
    filename,
  };
}

/**
 * Merges main document PDF buffer with user attached PDF files into a single Uint8Array PDF
 */
export async function mergeMainPdfWithAttachments(
  mainPdfBuffer: ArrayBuffer,
  attachmentFiles: File[]
): Promise<Uint8Array> {
  const { PDFDocument } = await import('pdf-lib');
  const mergedPdfDoc = await PDFDocument.create();

  // 1. Copy pages from the main document PDF
  const mainPdf = await PDFDocument.load(mainPdfBuffer);
  const mainPages = await mergedPdfDoc.copyPages(mainPdf, mainPdf.getPageIndices());
  mainPages.forEach((page) => mergedPdfDoc.addPage(page));

  // 2. Copy pages from each attached PDF file
  for (const file of attachmentFiles) {
    try {
      const fileBuffer = await file.arrayBuffer();
      const attachedPdf = await PDFDocument.load(fileBuffer);
      const attachedPages = await mergedPdfDoc.copyPages(attachedPdf, attachedPdf.getPageIndices());
      attachedPages.forEach((page) => mergedPdfDoc.addPage(page));
    } catch (err) {
      console.error(`Error merging attached PDF ${file.name}:`, err);
    }
  }

  return await mergedPdfDoc.save();
}

/**
 * Converts File object to Base64 string (without data URL prefix)
 */
export function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      const base64 = result.includes(',') ? result.split(',')[1] : result;
      resolve(base64);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}
